-- db/02-rooms.sql
-- GENERATED FILE — do not edit by hand.
-- Source of truth: tools/floor_geometry.py ROOM_DIRECTORY,
-- regenerated by tools/render_floor_maps.py.

CREATE TABLE IF NOT EXISTS rooms (
    room_id     TEXT    PRIMARY KEY,
    floor       INTEGER NOT NULL,
    name        TEXT    NOT NULL,
    col_start   INTEGER NOT NULL,
    col_end     INTEGER NOT NULL,
    row_start   INTEGER NOT NULL,
    row_end     INTEGER NOT NULL
);

TRUNCATE TABLE rooms;

INSERT INTO rooms (room_id, floor, name, col_start, col_end, row_start, row_end) VALUES
    ('358', 3, 'Health & Personal Care', 48, 120, 47, 85),
    ('357', 3, 'Laptop Accessories', 124, 194, 47, 85),
    ('356', 3, 'Gaming', 197, 236, 47, 85),
    ('355', 3, 'Smart Wearables', 268, 302, 47, 85),
    ('354', 3, 'Smart Home Automation', 305, 339, 47, 85),
    ('353', 3, 'Storage', 342, 376, 47, 85),
    ('352', 3, 'Mobile & Tablets Hub', 379, 413, 47, 85),
    ('351', 3, 'Computer Systems Hub', 416, 450, 47, 85),
    ('350', 3, 'Smart Devices Hub', 453, 474, 47, 85),
    ('462', 4, 'Pet and Gardening', 2, 34, 55, 95),
    ('461', 4, 'Cleaning and Bath', 38, 71, 55, 95),
    ('460', 4, 'Lighting and Electricals', 74, 107, 55, 95),
    ('459', 4, 'Tools and utility', 111, 143, 55, 95),
    ('458', 4, 'Home Decor', 147, 180, 55, 95),
    ('457', 4, 'Kitchen and Dining', 183, 216, 55, 95),
    ('456', 4, 'Furnishings', 219, 252, 55, 95),
    ('455', 4, 'Bathroom', 256, 289, 55, 95),
    ('454', 4, 'Dining Room', 292, 325, 55, 95),
    ('453', 4, 'Kitchen', 328, 368, 55, 95),
    ('452', 4, 'Study/Office', 371, 411, 55, 95),
    ('451', 4, 'Living Room', 414, 443, 55, 95),
    ('450', 4, 'Bedroom', 446, 473, 55, 95);
