"""
tools/render_floor_maps.py

Offline build utility — NOT part of the running dashboard or server.

Generates, from the real floor grid arrays (maps/floor_*_grid.npy):
  1. dashboard/assets/floor_*.svg   — lossless vector floor plans with
     room number + store name labels baked in (Google-Maps style, bottom
     of each labeled room), plus a subtle corridor highlight.
  2. dashboard/assets/floor_*.png   — raster preview, kept for any tooling
     that prefers a bitmap (e.g. quick image viewers, older browsers).
  3. server/floors.json             — single source of truth for floor
     metadata: dimensions, corridor_rows, meters_per_cell, the room
     directory (id/name/bounding box), and corridor_segments (the
     corridor's own heatmap tiles — see floor_geometry.build_corridor_segments).
     Preserves any manually-calibrated meters_per_cell / origin across
     re-renders.
  4. db/02-rooms.sql                — generated seed for the `rooms` table,
     produced from the exact same Room objects used for the SVG labels and
     floors.json, so the database and the frontend can never drift apart.

Re-run this whenever the navigation team regenerates floor_*_grid.npy, or
whenever ROOM_DIRECTORY in tools/floor_geometry.py changes.

Usage:
    python tools/render_floor_maps.py
"""

from __future__ import annotations

import json
import os

import numpy as np
from PIL import Image

import floor_geometry as geo

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

GRIDS = {
    3: os.path.join(BASE_DIR, "maps", "floor_3_grid.npy"),
    4: os.path.join(BASE_DIR, "maps", "floor_4_grid.npy"),
}

ASSETS_DIR = os.path.join(BASE_DIR, "dashboard", "assets")
FLOORS_JSON_PATH = os.path.join(BASE_DIR, "server", "floors.json")
ROOMS_SQL_PATH = os.path.join(BASE_DIR, "db", "02-rooms.sql")

# Real, physically-measured building footprint. Both floors share this
# footprint (they're stacked levels of the same building), but the two
# floor grids don't have identical pixel dimensions (floor 3 is 477x89,
# floor 4 is 476x99) — a few extra rows/cols of margin baked into one grid
# vs the other means a single meters_per_cell can't make BOTH axes exactly
# correct on both floors simultaneously (a real, measured mismatch: see
# docs/CALIBRATION.md for the exact numbers). We calibrate off LENGTH
# (cols), not width (rows), because a straight corridor run is the
# dimension most reliably measured on-site with a single tape-measure
# pull, whereas "width" of an irregular retail floor (varying room depths,
# doorway recesses) is more likely to be an approximate figure to begin
# with. If you re-measure and find width is actually the more trustworthy
# number for your site, swap which axis this divides by.
REAL_FLOOR_LENGTH_METERS = 93.0
REAL_FLOOR_WIDTH_METERS = 15.765


def real_meters_per_cell(cols: int) -> float:
    return REAL_FLOOR_LENGTH_METERS / cols


# Devices walk only the corridor, which is grid-aligned (see phone.py), so
# one grid cell == one published coordinate unit. This is not a physical
# meters-per-cell calibration — it is set so the dashboard's existing
# meters_per_cell-based projection draws cell-aligned coordinates correctly.
# Replace with a real physical calibration once beacon-based fingerprinting
# positions are used instead of the simulator.
DEFAULT_UNITS_PER_CELL = 1.0

UPSCALE = 4  # PNG preview only — the SVG is already infinitely sharp


def render_png_preview(grid: np.ndarray, out_path: str) -> None:
    rows, cols = grid.shape
    rgba = np.zeros((rows, cols, 4), dtype=np.uint8)
    palette = {
        0: (14, 42, 61, 255),
        geo.WALL_VALUE: (232, 222, 200, 255),
        geo.ZONE2_VALUE: (31, 169, 199, 255),
        geo.ZONE3_VALUE: (242, 163, 60, 255),
    }
    for value, color in palette.items():
        rgba[grid == value] = color

    img = Image.fromarray(rgba, mode="RGBA")
    img = img.resize((cols * UPSCALE, rows * UPSCALE), Image.NEAREST)
    img.save(out_path)


def load_existing_floors_config() -> dict:
    if os.path.exists(FLOORS_JSON_PATH):
        with open(FLOORS_JSON_PATH) as f:
            return json.load(f)
    return {}


def room_to_dict(room: geo.Room) -> dict:
    return {
        "id": room.room_id,
        "name": room.name,
        "col_start": room.col_start,
        "col_end": room.col_end,
        "row_start": room.row_start,
        "row_end": room.row_end,
    }


def corridor_segment_to_dict(segment: geo.CorridorSegment) -> dict:
    return {
        "id": segment.segment_id,
        "col_start": segment.col_start,
        "col_end": segment.col_end,
        "row_start": segment.row_start,
        "row_end": segment.row_end,
    }


def write_rooms_sql(all_rooms: dict[int, list[geo.Room]], path: str) -> None:
    lines = [
        "-- db/02-rooms.sql",
        "-- GENERATED FILE — do not edit by hand.",
        "-- Source of truth: tools/floor_geometry.py ROOM_DIRECTORY,",
        "-- regenerated by tools/render_floor_maps.py.",
        "",
        "CREATE TABLE IF NOT EXISTS rooms (",
        "    room_id     TEXT    PRIMARY KEY,",
        "    floor       INTEGER NOT NULL,",
        "    name        TEXT    NOT NULL,",
        "    col_start   INTEGER NOT NULL,",
        "    col_end     INTEGER NOT NULL,",
        "    row_start   INTEGER NOT NULL,",
        "    row_end     INTEGER NOT NULL",
        ");",
        "",
        "TRUNCATE TABLE rooms;",
        "",
        "INSERT INTO rooms (room_id, floor, name, col_start, col_end, row_start, row_end) VALUES",
    ]

    value_lines = []
    for floor in sorted(all_rooms):
        for room in all_rooms[floor]:
            name_escaped = room.name.replace("'", "''")
            value_lines.append(
                f"    ('{room.room_id}', {room.floor}, '{name_escaped}', "
                f"{room.col_start}, {room.col_end}, {room.row_start}, {room.row_end})"
            )
    lines.append(",\n".join(value_lines) + ";")
    lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))


def main() -> None:
    os.makedirs(ASSETS_DIR, exist_ok=True)
    config = load_existing_floors_config()
    all_rooms: dict[int, list[geo.Room]] = {}

    for floor, grid_path in GRIDS.items():
        floor_key = str(floor)
        grid = np.load(grid_path)
        rows, cols = grid.shape

        corridor_band = geo.detect_corridor_band(grid)
        rooms, room_row_span = geo.build_rooms_for_floor(floor, grid, corridor_band)
        all_rooms[floor] = rooms

        svg = geo.render_floor_svg(grid, rooms, corridor_band)
        svg_path = os.path.join(ASSETS_DIR, f"floor_{floor}.svg")
        with open(svg_path, "w") as f:
            f.write(svg)

        png_path = os.path.join(ASSETS_DIR, f"floor_{floor}.png")
        render_png_preview(grid, png_path)

        existing = config.get(floor_key, {})
        # .get(key, default) only falls back when the key is ABSENT — but the
        # previous floors.json always had this key present with value null
        # (uncalibrated) or the old 1.0 grid-cell placeholder. Treat both the
        # same as "absent": fill in the real physical calibration. A
        # deliberately hand-set calibration (anything other than null or the
        # retired 1.0 placeholder) is preserved across re-renders.
        prior_mpc = existing.get("meters_per_cell")
        if prior_mpc is None or prior_mpc == DEFAULT_UNITS_PER_CELL:
            meters_per_cell = real_meters_per_cell(cols)
        else:
            meters_per_cell = prior_mpc

        corridor_segments = geo.build_corridor_segments(
            floor, cols, corridor_band, meters_per_cell
        )

        config[floor_key] = {
            "cols": cols,
            "rows": rows,
            "image": f"assets/floor_{floor}.svg",
            "meters_per_cell": meters_per_cell,
            "origin": existing.get("origin", {"col": 0, "row": 0}),
            "corridor_rows": list(corridor_band),
            "corridor_segments": [corridor_segment_to_dict(s) for s in corridor_segments],
            "rooms": [room_to_dict(r) for r in rooms],
        }

        implied_width = rows * meters_per_cell
        print(
            f"Floor {floor}: {cols}x{rows} cells | "
            f"corridor_rows={corridor_band} | rooms={len(rooms)} | "
            f"corridor_segments={len(corridor_segments)} | "
            f"meters_per_cell={meters_per_cell:.5f} (calibrated to "
            f"{REAL_FLOOR_LENGTH_METERS}m length) -> implied width "
            f"{implied_width:.2f}m vs stated {REAL_FLOOR_WIDTH_METERS}m | "
            f"wrote {svg_path}"
        )

    with open(FLOORS_JSON_PATH, "w") as f:
        json.dump(config, f, indent=2)
    print(f"\nUpdated {FLOORS_JSON_PATH}")

    write_rooms_sql(all_rooms, ROOMS_SQL_PATH)
    print(f"Updated {ROOMS_SQL_PATH}")


if __name__ == "__main__":
    main()